### ISSUE TITLE
[BUG] NPE on app startup

### ISSUE THREAD

**Issue by ThatMG393** [Raidenxd2/PojavLauncher-community#2]
### Describe the bug

Application crashed immediately on startup

### The log file and images/videos

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at net.kdt.pojavlaunch.fragments.MainMenuFragment.onViewCreated(MainMenuFragment.java:54)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at net.kdt.pojavlaunch.LauncherActivity.onStart(LauncherActivity.java:188)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8616)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Steps To Reproduce

```markdown
1. Have OneUI 5.1 & Android 13
2. Start PojavLauncher (Minecraft: Java Edition for Android) (Community Edition)
```

### Expected Behavior

I expect the app to launch fine

### Platform

```markdown
- Device model: Scamsung A13B
- CPU architecture: armv8l
- Android version: 13
- PojavLauncher version: Latest Action Build
```

### Anything else?

capybara

**Comment by Raidenxd2** [comment]
Weird that it's crashing on something that's in normal PojavLauncher (setting the reference for the profile edit button).
Sadly, I don't have an Android 13 device running OneUI 5.1 though I could try an emulator running Android 13.
Also I have an Android 12 device running OneUI 4.1
and what does NPE mean?

**Comment by Raidenxd2** [comment]
Seems like it happens on Android 13.
![studio64_6w7RJ3xWMp](https://user-images.githubusercontent.com/64755433/228996258-91b4a7d9-9af8-4991-831b-e354f104f352.png)
![scrcpy_z2P9kQJZyd](https://user-images.githubusercontent.com/64755433/228996398-7654e6d5-719d-4914-b5af-97b36a50b6c3.png)
Top image is an emulator running Android 13.
Bottom image is my tablet running OneUI 4.1 with Android 12.

**Comment by Raidenxd2** [comment]
Fixed in latest commit, please install the new version from GitHub Actions and tell me if it fixes the problem.

**Comment by ThatMG393** [comment]
@Raidenxd2 Can confirm it's fixed, closing the issue.
